
import React from 'react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  Cell, PieChart, Pie, Legend, LineChart, Line
} from 'recharts';
import { TrainingResult, ProblemType } from '../types';
import { Trophy, Clock, Zap, BookOpen, AlertTriangle, Sparkles, Download, FileJson, Share2 } from 'lucide-react';

interface ResultsStepProps {
  result: TrainingResult;
  problemType: ProblemType;
}

const COLORS = ['#6366f1', '#818cf8', '#a5b4fc', '#c7d2fe', '#60a5fa', '#3b82f6'];

const ResultsStep: React.FC<ResultsStepProps> = ({ result, problemType }) => {
  const isClassification = problemType === ProblemType.CLASSIFICATION;
  
  const metricData = Object.entries(result.metrics).map(([name, value]) => {
    const numValue = typeof value === 'number' ? value : 0;
    return {
      name,
      value: (name === 'Accuracy' || name === 'F1-Score' || name === 'R² Score') ? Math.round(numValue * 100) : numValue,
      display: (name === 'Accuracy' || name === 'F1-Score' || name === 'R² Score') ? `${Math.round(numValue * 100)}%` : numValue.toFixed(2)
    };
  });

  const exportReport = () => {
    const reportContent = `
      <html>
        <head><title>ML Ease - Auto ML Report</title></head>
        <body style="font-family: sans-serif; padding: 40px; color: #333;">
          <h1>ML Ease Training Report</h1>
          <p>Model: ${result.modelName}</p>
          <p>Trained At: ${result.timestamp}</p>
          <hr/>
          <h2>Performance Metrics</h2>
          <ul>
            ${Object.entries(result.metrics).map(([k, v]) => {
              // Fix: Explicitly cast the metric value to number to access toFixed
              return `<li>${k}: ${(v as number).toFixed(4)}</li>`;
            }).join('')}
          </ul>
          <h2>Hyperparameters</h2>
          <pre>${JSON.stringify(result.params, null, 2)}</pre>
          <hr/>
          <p>Generated by ML Ease AI platform.</p>
        </body>
      </html>
    `;
    const blob = new Blob([reportContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ML-Ease-Report-${result.modelName}.html`;
    a.click();
  };

  const downloadModel = () => {
    // Mock .pkl serialization
    const mockModel = {
      model_id: Math.random().toString(36).substr(2, 9),
      name: result.modelName,
      metrics: result.metrics,
      params: result.params,
      binary: "U0VSSUFMSVpFRF9NT0RFTF9EQVRBX0hFUkU="
    };
    const blob = new Blob([JSON.stringify(mockModel)], { type: 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.modelName.replace(/\s+/g, '_').toLowerCase()}_model.pkl`;
    a.click();
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
      {/* Actions Bar */}
      <div className="flex flex-wrap gap-4 items-center justify-between bg-white p-6 rounded-3xl border border-slate-100 shadow-sm">
         <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-indigo-600 text-white rounded-2xl flex items-center justify-center shadow-lg shadow-indigo-100">
               <Trophy size={24} />
            </div>
            <div>
               <h3 className="font-bold text-slate-800">{result.modelName} Trained Successfully</h3>
               <p className="text-xs text-slate-400">Evaluation complete at {result.timestamp}</p>
            </div>
         </div>
         <div className="flex gap-3">
            <button onClick={exportReport} className="flex items-center gap-2 px-4 py-2 bg-slate-50 hover:bg-slate-100 text-slate-700 rounded-xl text-sm font-bold transition-all border border-slate-200">
               <Share2 size={16} />
               Export Report
            </button>
            <button onClick={downloadModel} className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-indigo-100">
               <Download size={16} />
               Download .pkl
            </button>
         </div>
      </div>

      {/* Top Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm space-y-1">
          <div className="text-indigo-600 bg-indigo-50 w-10 h-10 rounded-xl flex items-center justify-center mb-3">
            <Trophy size={20} />
          </div>
          <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Primary Metric</div>
          <div className="text-2xl font-black text-slate-800">
            {isClassification ? `${Math.round((result.metrics['Accuracy'] || 0) * 100)}%` : (result.metrics['R² Score'] || 0).toFixed(2)}
          </div>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm space-y-1">
          <div className="text-emerald-600 bg-emerald-50 w-10 h-10 rounded-xl flex items-center justify-center mb-3">
            <Clock size={20} />
          </div>
          <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Training Time</div>
          <div className="text-2xl font-black text-slate-800">{result.trainingTime.toFixed(2)}s</div>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm space-y-1">
          <div className="text-amber-600 bg-amber-50 w-10 h-10 rounded-xl flex items-center justify-center mb-3">
            <Zap size={20} />
          </div>
          <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">CV Avg Score</div>
          <div className="text-2xl font-black text-slate-800">
             {(result.cvFolds.reduce((a, b) => a + b.score, 0) / 5).toFixed(3)}
          </div>
        </div>
        <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm space-y-1">
          <div className="text-rose-600 bg-rose-50 w-10 h-10 rounded-xl flex items-center justify-center mb-3">
            <BookOpen size={20} />
          </div>
          <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Complexity</div>
          <div className="text-2xl font-black text-slate-800">{result.params.depth > 10 ? 'High' : 'Medium'}</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Main Metrics Chart */}
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm space-y-6">
           <div className="flex justify-between items-center">
              <h4 className="font-bold text-slate-800 text-lg">Detailed Metrics</h4>
              <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg">
                 <FileJson size={18} />
              </div>
           </div>
           <div className="h-[320px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={metricData} layout="vertical" margin={{ left: 20, right: 20, top: 10 }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f1f5f9" />
                  <XAxis type="number" hide />
                  <YAxis dataKey="name" type="category" width={100} tick={{ fontSize: 11, fontWeight: 500, fill: '#64748b' }} axisLine={false} tickLine={false} />
                  <Tooltip 
                    cursor={{ fill: '#f8fafc' }}
                    content={({ active, payload }) => {
                      if (active && payload && payload.length) {
                        return (
                          <div className="bg-white p-3 shadow-xl rounded-xl border border-slate-100">
                             <p className="text-xs font-bold text-slate-800">{payload[0].payload.name}</p>
                             <p className="text-lg font-black text-indigo-600">{payload[0].payload.display}</p>
                          </div>
                        );
                      }
                      return null;
                    }}
                  />
                  <Bar dataKey="value" radius={[0, 8, 8, 0]} barSize={24}>
                    {metricData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
           </div>
        </div>

        {/* Cross-Validation Visualization */}
        <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm space-y-6">
           <h4 className="font-bold text-slate-800 text-lg">Cross-Validation Stability (5-Fold)</h4>
           <div className="h-[320px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={result.cvFolds} margin={{ top: 20, right: 30, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis dataKey="fold" tick={{ fontSize: 11 }} axisLine={false} />
                  <YAxis domain={['dataMin - 0.1', 'dataMax + 0.1']} hide />
                  <Tooltip />
                  <Line type="monotone" dataKey="score" stroke="#6366f1" strokeWidth={4} dot={{ r: 6, fill: '#6366f1' }} activeDot={{ r: 8 }} />
                </LineChart>
              </ResponsiveContainer>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
         {/* Confusion Matrix / Classification Visual */}
         {isClassification && (
           <div className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm space-y-6">
              <h4 className="font-bold text-slate-800 text-lg">Confusion Matrix</h4>
              <div className="grid grid-cols-2 gap-4">
                 {result.confusionMatrix?.map((row, rIdx) => (
                    row.map((val, cIdx) => (
                       <div key={`${rIdx}-${cIdx}`} className={`p-8 rounded-2xl flex flex-col items-center justify-center border ${
                          rIdx === cIdx ? 'bg-indigo-50 border-indigo-100' : 'bg-slate-50 border-slate-100 opacity-60'
                       }`}>
                          <span className="text-3xl font-black text-slate-800">{val}</span>
                          <span className="text-[10px] uppercase font-bold text-slate-400 mt-2">
                             {rIdx === 0 ? 'Actual Positive' : 'Actual Negative'} / {cIdx === 0 ? 'Pred Positive' : 'Pred Negative'}
                          </span>
                       </div>
                    ))
                 ))}
              </div>
           </div>
         )}

        {/* Feature Importance */}
        <div className={`${isClassification ? '' : 'lg:col-span-2'} bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm space-y-6`}>
           <h4 className="font-bold text-slate-800 text-lg">Feature Contribution</h4>
           <div className="h-[320px] w-full">
              {result.featureImportance && result.featureImportance.length > 0 ? (
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={result.featureImportance}
                      cx="50%"
                      cy="45%"
                      innerRadius={60}
                      outerRadius={90}
                      paddingAngle={5}
                      dataKey="score"
                      nameKey="name"
                    >
                      {result.featureImportance.map((entry, index) => (
                        <Cell key={`cell-pie-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip />
                    <Legend verticalAlign="bottom" height={36} wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
                  </PieChart>
                </ResponsiveContainer>
              ) : null}
           </div>
        </div>
      </div>

      {/* AI Explanation Section */}
      <div className="bg-indigo-900 rounded-[2.5rem] p-10 text-white shadow-2xl shadow-indigo-200 relative overflow-hidden">
        <div className="absolute top-0 right-0 p-8 text-white/5">
           <BookOpen size={160} />
        </div>
        <div className="relative z-10 max-w-3xl">
           <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/10 text-indigo-200 rounded-full text-[10px] font-bold uppercase tracking-widest mb-4 border border-white/10">
              <Sparkles size={12} />
              AI Reasoning
           </div>
           <h3 className="text-2xl font-bold mb-6">Pipeline Interpretability</h3>
           <div className="space-y-6 text-indigo-100/80 leading-relaxed text-sm">
             <p className="whitespace-pre-wrap">{result.explanation || "Generating deep analysis..."}</p>
             
             <div className="p-6 bg-white/5 border border-white/10 rounded-2xl space-y-3">
                <div className="flex items-center gap-2 text-white font-bold">
                   <AlertTriangle size={18} className="text-amber-400" />
                   Model Bias & Robustness
                </div>
                <p className="text-xs">
                   The model shows consistent scores across 5 folds, indicating low variance and healthy generalization.
                   However, the high contribution of <strong>{result.featureImportance[0]?.name}</strong> means the model depends heavily on this single feature.
                </p>
             </div>
           </div>
        </div>
      </div>
    </div>
  );
};

export default ResultsStep;
